### ISSUE TITLE
一些添加建议

### ISSUE THREAD

**Issue by ghost** [stackia/best-windows-apps#5]
截图软件还可以推荐一下Snipaste
官网：https://zh.snipaste.com/ 
文档：https://docs.snipaste.com/zh-cn/  

此外，CCleaner由于经常损坏Windows 系统文件，已经被Microsoft Community封杀了,个人是不推荐这个软件的

**Comment by Aic9182** [comment]
此外，Windows 自带的便签也不错

**Comment by krisfans** [comment]
> 
> 
> 截图软件还可以推荐一下Snipaste
> 官网：https://zh.snipaste.com/
> 文档：https://docs.snipaste.com/zh-cn/
> 
> 此外，CCleaner由于经常损坏Windows 系统文件，已经被Microsoft Community封杀了,个人是不推荐这个软件的

赞同

**Comment by stackia** [comment]
已添加，谢谢建议
